services:
  db:
    image: postgres:15-alpine
    container_name: portal_db
    restart: always
    environment:
      POSTGRES_DB: portaldatabase
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
    ports:
      - "5433:5432" 
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend             # Diz pro Docker ler o Dockerfile da pasta backend
    container_name: portal_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app           # Sincroniza seu código em tempo real
    depends_on:
      - db                       # Só liga depois que o banco estiver pronto
    environment:
      - DB_HOST=db               # A MÁGICA ACONTECE AQUI (Explico abaixo)
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"

  frontend:
    build: ./frontend            # Diz pro Docker ler o Dockerfile da pasta frontend
    container_name: portal_frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app          # Sincroniza seu código do React em tempo real
      - /app/node_modules        # Protege as dependências do contêiner
    depends_on:
      - backend

volumes:
  postgres_data: