repo_url: https://github.com/mdsreq-fga-unb/REQ-2026.1-T01-PortalEntreAmigos
repo_name: 2026.1-Grupo01

site_url: https://mdsreq-fga-unb.github.io/REQ-2026.1-T01-PortalEntreAmigos/
site_name: Projeto de Requisitos de Software - Grupo 01
site_description: Documentação do Projeto de Requisitos de Software - Grupo 01
site_author: Grupo 01 - 2026.1

nav:
  - Home: index.md
  
  - Visão Geral do Projeto:

     - Cliente e Negócio:
        - Visão Geral do Cliente: 01_Cliente/visao_geral.md
        - Análise do Problema: 01_Cliente/analise_problema.md
        - Stakeholders e Usuários: 01_Cliente/stakeholders.md

     - Solução Proposta:
        - Objetivos e Produto: 02_solucao/produto.md
        - Tecnologias e Viabilidade: 02_solucao/tecnologias_viabilidade.md

     - Intervenção Social: 03_intervencao_social/intervencao_social.md

     - Estratégias: 03_estrategia/estrategias.md

     - Engenharia de Requisitos: 04_engenharia_requisitos/engenharia_requisitos.md

     - Cronograma e Entregas: 05_cronograma/cronograma.md

     - Equipe e Cliente: 06_equipe_cliente/equipe_cliente.md

     - Requisitos de Software: 13_requisitos/requisitos.md

     - DoR e DoD: 14_dor_dod/dor_dod.md

     - Backlog do Produto: 
        - Backlog Geral: 15_backlog/backlog.md
        - Priorização do Backlog e MVP: 15_backlog/priorizacao.md
        - Criterios de Aceitação: 15_backlog/criterios_aceitacao.md

  - Ciclos RAD:
    - Ciclo 1:
      - Fases do RAD: 16_ciclos_rad/ciclo1/fases_rad.md
      - DOR e DOD: 16_ciclos_rad/ciclo1/dor_dod_evidencias.md
      - Critérios de Aceitação: 16_ciclos_rad/ciclo1/criterios_evidencias.md
    - Ciclo 2:
      - Fases do RAD: 16_ciclos_rad/ciclo2/fases_rad.md
      - DOR e DOD: 16_ciclos_rad/ciclo2/dor_dod_evidencias.md
      - Critérios de Aceitação: 16_ciclos_rad/ciclo2/criterios_evidencias.md
    - Ciclo 3:
      - RF01:
        - Fases do RAD: 16_ciclos_rad/ciclo3/RF01/fases_rad_RF01.md
        - DOR e DOD: 16_ciclos_rad/ciclo3/RF01/dor_dod_evidencias_RF01.md
        - Critérios de Aceitação: 16_ciclos_rad/ciclo3/RF01/criterios_evidencias_RF01.md
      - RF02:
        - Fases do RAD: 16_ciclos_rad/ciclo3/RF02/fases_rad_RF02.md
        - DOR e DOD: 16_ciclos_rad/ciclo3/RF02/dor_dod_evidencias_RF02.md
        - Critérios de Aceitação: 16_ciclos_rad/ciclo3/RF02/criterios_evidencias_RF02.md
      - RF03:
        - Fases do RAD: 16_ciclos_rad/ciclo3/RF03/fases_rad_RF03.md
        - DOR e DOD: 16_ciclos_rad/ciclo3/RF03/dor_dod_evidencias_RF03.md
        - Critérios de Aceitação: 16_ciclos_rad/ciclo3/RF03/criterios_evidencias_RF03.md
      - RF04:
        - Fases do RAD: 16_ciclos_rad/ciclo3/RF04/fases_rad_RF04.md
        - DOR e DOD: 16_ciclos_rad/ciclo3/RF04/dor_dod_evidencias_RF04.md
        - Critérios de Aceitação: 16_ciclos_rad/ciclo3/RF04/criterios_evidencias_RF04.md
      - RF05:
        - Fases do RAD: 16_ciclos_rad/ciclo3/RF05/fases_rad_RF05.md
        - DOR e DOD: 16_ciclos_rad/ciclo3/RF05/dor_dod_evidencias_RF05.md
        - Critérios de Aceitação: 16_ciclos_rad/ciclo3/RF05/criterios_evidencias_RF05.md
    - Ciclo 4:
      - RF06:
        - Fases do RAD: 16_ciclos_rad/ciclo4/RF06/fases_rad_RF06.md
        - DOR e DOD: 16_ciclos_rad/ciclo4/RF06/dor_dod_evidencias_RF06.md
        - Critérios de Aceitação: 16_ciclos_rad/ciclo4/RF06/criterios_evidencias_RF06.md
      - RF07:
        - Fases do RAD: 16_ciclos_rad/ciclo4/RF07/fases_rad_RF07.md
        - DOR e DOD: 16_ciclos_rad/ciclo4/RF07/dor_dod_evidencias_RF07.md
        - Critérios de Aceitação: 16_ciclos_rad/ciclo4/RF07/criterios_evidencias_RF07.md
      - RF08:
        - Fases do RAD: 16_ciclos_rad/ciclo4/RF08/fases_rad_RF08.md
        - DOR e DOD: 16_ciclos_rad/ciclo4/RF08/dor_dod_evidencias_RF08.md
        - Critérios de Aceitação: 16_ciclos_rad/ciclo4/RF08/criterios_evidencias_RF08.md
    - Ciclo 5:
      - RF10:
        - Fases do RAD: 16_ciclos_rad/ciclo5/RF10/fases_rad_RF10.md
        - DOR e DOD: 16_ciclos_rad/ciclo5/RF10/dor_dod_evidencias_RF10.md
        - Critérios de Aceitação: 16_ciclos_rad/ciclo5/RF10/criterios_evidencias_RF10.md
      - RF11:
        - Fases do RAD: 16_ciclos_rad/ciclo5/RF11/fases_rad_RF11.md
        - DOR e DOD: 16_ciclos_rad/ciclo5/RF11/dor_dod_evidencias_RF11.md
        - Critérios de Aceitação: 16_ciclos_rad/ciclo5/RF11/criterios_evidencias_RF11.md

  - Planejamento e Organização:
    - Planejamento: 17_plan_organ/planejamento.md
    - Rastreabilidade dos Ciclos:
      - Ciclo 1: 17_plan_organ/rastreabilidade/ciclo1.md
      - Ciclo 2: 17_plan_organ/rastreabilidade/ciclo2.md
      - Ciclo 3: 17_plan_organ/rastreabilidade/ciclo3.md
      - Ciclo 4: 17_plan_organ/rastreabilidade/ciclo4.md
      - Ciclo 5: 17_plan_organ/rastreabilidade/ciclo5.md
      - Ciclo 6: 17_plan_organ/rastreabilidade/ciclo6.md
      - Ciclo 7: 17_plan_organ/rastreabilidade/ciclo7.md
    - MVP: 17_plan_organ/MVP/mvp.md
    
  - Lições Aprendidas:
    - Unidade 1: 10_licoes/Unidades/unidade_01.md
    - Unidade 2: 10_licoes/Unidades/unidade_02.md
    - Unidade 3: 10_licoes/Unidades/unidade_03.md

  - Reuniões/Gravações:
    - Gravações em Grupo: 12_reunioes/gravacoes_grupo.md
    - Gravações com Cliente: 12_reunioes/gravacoes.md
    - Atas:
      - Grupo:
         - Ata de Reunião 1: 12_reunioes/atas/grupo/ata_grupo_01.md
         - Ata de Reunião 2: 12_reunioes/atas/grupo/ata_grupo_02.md
         - Ata de Reunião 3: 12_reunioes/atas/grupo/ata_grupo_03.md
         - Ata de Reunião 4: 12_reunioes/atas/grupo/ata_grupo_04.md
         - Ata de Reunião 5: 12_reunioes/atas/grupo/ata_grupo_05.md
         - Ata de Reunião 6: 12_reunioes/atas/grupo/ata_grupo_06.md
         - Ata de Reunião 7: 12_reunioes/atas/grupo/ata_grupo_07.md
         - Ata de Reunião 8: 12_reunioes/atas/grupo/ata_grupo_08.md
         - Ata de Reunião 9: 12_reunioes/atas/grupo/ata_grupo_09.md
         - Ata de Reunião 10: 12_reunioes/atas/grupo/ata_grupo_10.md
         - Ata de Reunião 11: 12_reunioes/atas/grupo/ata_grupo_11.md
         - Ata de Reunião 12: 12_reunioes/atas/grupo/ata_grupo_12.md
         - Ata de Reunião 13: 12_reunioes/atas/grupo/ata_grupo_13.md
         - Ata de Reunião 14: 12_reunioes/atas/grupo/ata_grupo_14.md
         - Ata de Reunião 15: 12_reunioes/atas/grupo/ata_grupo_15.md
         - Ata de Reunião 16: 12_reunioes/atas/grupo/ata_grupo_16.md
         - Ata de Reunião 17: 12_reunioes/atas/grupo/ata_grupo_17.md
         - Ata de Reunião 18: 12_reunioes/atas/grupo/ata_grupo_18.md
         - Ata de Reunião 19: 12_reunioes/atas/grupo/ata_grupo_19.md
         - Ata de Reunião 20: 12_reunioes/atas/grupo/ata_grupo_20.md
         - Ata de Reunião 21: 12_reunioes/atas/grupo/ata_grupo_21.md
      - Cliente:
         - Ata de Reunião 1 com Cliente: 12_reunioes/atas/cliente/ata_cliente_01.md
         - Ata de Reunião 2 com Cliente: 12_reunioes/atas/cliente/ata_cliente_02.md
         - Ata de Reunião 3 com Cliente: 12_reunioes/atas/cliente/ata_cliente_03.md
         - Ata de Reunião 4 com Cliente: 12_reunioes/atas/cliente/ata_cliente_04.md
         - Ata de Reunião 5 com Cliente: 12_reunioes/atas/cliente/ata_cliente_05.md
         - Ata de Reunião 6 com Cliente: 12_reunioes/atas/cliente/ata_cliente_06.md
         - Ata de Reunião 7 com Cliente: 12_reunioes/atas/cliente/ata_cliente_07.md
         - Ata de Reunião 8 com Cliente: 12_reunioes/atas/cliente/ata_cliente_08.md
         - Ata de Reunião 9 com Cliente: 12_reunioes/atas/cliente/ata_cliente_09.md
         - Ata de Reunião 10 com Cliente: 12_reunioes/atas/cliente/ata_cliente_10.md




theme:
  name: material
  logo: 00_assets/imagens/logo_1.png
  favicon: 00_assets/imagens/logo_2.png
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.top
    - search.suggest
    - search.highlight
  palette:
    - scheme: default
      primary: deep orange
      accent: orange
      toggle:
        icon: material/weather-night
        name: Modo Noturno
    - scheme: slate
      primary: deep orange
      accent: orange
      toggle:
        icon: material/weather-sunny
        name: Modo Claro


markdown_extensions:
  - pymdownx.emoji
  - pymdownx.tasklist
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.highlight
  - pymdownx.superfences
  - toc:
      permalink: true
  - attr_list