repo_url: https://mdsreq-fga-unb.github.io/REQ-2026.1-T01-PortalEntreAmigos/
repo_name: 2026.1-Grupo01

site_name: Projeto de Requisitos de Software - Grupo 01
site_description: Documentação do Projeto de Requisitos de Software - Grupo 01
site_author: Grupo 01 - 2026.1

nav:
  - Home: index.md
  
  - Cliente e Negócio: 
    - Introdução ao Cliente e Negócio: 01_Cliente/intro.md
    - Rich Picture: 01_Cliente/rich_picture.md
    - Desafios do Projeto: 01_Cliente/desafios.md
    - Mapa de Stakeholders: 01_Cliente/mapa_stakeholders.md
    - Segmentação de Clientes: 01_Cliente/segmentacao.md

  - Solução Proposta: 
    - Objetivo: 02_solucao/objetivo.md
    - Características do Produto: 02_solucao/produto.md
    - Tecnologias a Serem Utilizadas: 02_solucao/tecnologias.md
    - Pesquisa de Mercado: 02_solucao/pesquisa_mercado.md
    - Viabilidade e Benefícios: 02_solucao/viabilidade.md

  - Estratégias: 03_estrategia/estrategias.md

  - Engenharia de Requisitos: 04_engenharia_requisitos/engenharia_requisitos.md

  - Cronograma e Entregas: 05_cronograma/cronograma.md

  - Equipe e Cliente: 06_equipe_cliente/equipe_cliente.md




theme:
  name: material
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.top
    - search.suggest
    - search.highlight
  palette:
    - scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/weather-night
        name: Modo Noturno
    - scheme: slate
      primary: green
      accent: light blue
      toggle:
        icon: material/weather-sunny
        name: Modo Claro


markdown_extensions:
  - pymdownx.emoji
  - pymdownx.tasklist
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.highlight
  - pymdownx.superfences
  - toc:
      permalink: true
  - attr_list