# Generated by Django 6.0.6 on 2026-06-21 02:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_perfilusuario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doacao',
            name='doador_email',
        ),
        migrations.RemoveField(
            model_name='doacao',
            name='doador_nome',
        ),
        migrations.RemoveField(
            model_name='itemdoacao',
            name='quantidade_arrecadada',
        ),
        migrations.AddField(
            model_name='doacao',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('RECEBIDA', 'Recebida')], default='PENDENTE', max_length=10),
        ),
        migrations.AddField(
            model_name='doacao',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='doacoes', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itemdoacao',
            name='quantidade_prometida',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='itemdoacao',
            name='quantidade_recebida',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
