# Generated by Django 6.0.6 on 2026-06-21 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_promessa_doacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='pontos_coleta',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
