# Generated by Django 6.0.6 on 2026-06-21 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_evento_pontos_coleta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='local',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
