# Generated by Django 6.0.6 on 2026-06-25 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_codigorecuperacaosenha'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='imagens_banner',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
