# Generated by Django 6.0.6 on 2026-06-25 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_evento_imagens_banner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='imagens_banner',
        ),
    ]
