# Generated by Django 6.0.6 on 2026-06-25 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_evento_imagens_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemdoacao',
            name='unidade_medida',
            field=models.CharField(default='unidade', max_length=20),
        ),
    ]
