# Generated by Django 6.0.6 on 2026-06-25 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_itemdoacao_unidade_medida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='status',
            field=models.CharField(choices=[('EM_ANDAMENTO', 'Em andamento'), ('AGUARDANDO_RELATORIO', 'Aguardando Relatório'), ('CONCLUIDO', 'Concluído'), ('CANCELADO', 'Cancelado')], default='EM_ANDAMENTO', max_length=20),
        ),
    ]
