# Generated by Django 6.0.6 on 2026-06-25 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_evento_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardTransparencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('arquivo_pdf', models.FileField(upload_to='transparencia_pdfs/')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
