name: Docs CD - Deploy MkDocs

on:
  push:
    branches:
      - main
      - develop 

permissions:
  contents: write 

jobs:
  deploy:
    name: Publicar MkDocs no GitHub Pages
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Instalar dependências do MkDocs
        run: |
          pip install -r requirements.txt

      - name: Deploy da documentação
        run: |
          mkdocs gh-deploy --force